sudo: required
services:
  - docker
language: java
jdk: oraclejdk8
env:
  secure:
    - secure: hPv+micJY/ThAcprOxIgv2TDD55Fs6uAoHZTOhuoykY+R/6SAuXVunfIYwRPoEde1HqASseTNxR65EnV/zbN4CWv2M9gydTvgkgN08DuYdnOvz1E4B0xOy3l4J2d8U4uJY9SRWBI2aBro72NwL0xl+NyjfNJWx9o7YdkGxbe+mJKPQekbrx34b0h22PS9JOsIKsgMRUjm13/bTx26KgHIxIsUvLhihKtnq4c/HstFYjLwRlS76Lo7BGrEMBFC6eSsuxQnpf+6eOgsDVzBheXAtu+H97fRfAgZ2Qi7pF1RYwtih+w21hgTW1gBxpWkIEMcI6FkNnUMxBt0b6MnCFclJPmH6aS/uJ2AEhxcCLtUl8noGau7qhghc70k3V9RpP769F1Dymuu/6C25cVpJvdpJK8gGX7bbRSKSO43h6QDytpYVZrJ0Q7PAuD3QliLWbqrq5bqgGB+nQImn+J7PCu2RHS0D6EIh/UQH9sbBtFps4cBHJA6xEACaErAvnyKad0fW9u6EWu8LMb74RadwNpeD2nvbq/RBEA8Oo1mxouTOSYMiXRu/5mbPDLKxVgqPFbMd8X/YU9M97IMVNvWsqAJp95c257YyRjaV5BkFEy1r+421sNKU+q14aWtVOMTwBUzrEkDjq+6ghIJIhDVzJCSQaE3pRGc8Ur4QlWClvgkpY=
    - secure: ztX7dO25ipYLFRzOMVdnZGq7cVSzVjlzKBVFU3HTVftFcbqK7gIui8MQad/RobVFWLcvTMkqbhzPjKJnNxb8T0LMuLMR1KIAWTfqcZw0AuJYrkl9nS8RtRRXqLkWIhQxfy/10sDV2Sml9naLk43gvlLYQBbxy311UTOLNcCOcJjn0JJ5Jef+pl9nXQccnHZvvJSGrc6qAaRqJ62B/2CXhmn9etgYfPre8X6QCIrImkg6Wbp/+/tHrxr6EgVzMQRz/53zshx1X1/hG5gIn55fAxOV/o/aUOR9Z8ibgRrSBXY9kXtRM73KXYXyfL40bkd8DRJWjT4OUsc7UV7VsZFUiFuYO+oonbllRefhBRlWXPlFq8ap7Cw1WyL+CVjJY9mB857pAj4aDA8HsbjfMJxtZogt5W0w+mTJqBPWQX+tnPj/yKGsQC6kkrV1IgAalhxUiARnCNzrK59J00viYFDOHPXXCRH4Cw/I8e9rStl8tmtGnbys/C0/ONMMXBypzRsX+wQnjtYPA/pXXZbTwnzfE1bIBVwGQudb/p/jfu7h1hGmSigng56i2/Dcy9OhOUM8H9x8rrmYsWQL2GixPcQUL7aRmP28bMXIeQd8/9FJM0wqb5DefU4kaNMgkqIli05+0N1+g9TX3ZYPyCYHVDk1um3Pa0ZEOQ2FPsJYbFp9rKY= #DOCKER_USER
    - secure: xCtSRCzDP4qavLsU2PgZpVfIyFC/MrWpBAdPgDkQTU4rToRO104c7e6Xe9+PjDmxcD3JuOPKBUmz0V2fa1YdVz93daVxkjeTrCUhlt7bQDoTq36QoS8o/B6C30McfZj9TBuvIMPDn7Z3o39aXL7gws2cjuGsu3qMZHKWLLASY3refMsy8yXFcdkyV/KR7jvAun/Ua7LTWS5QaPJn4r6Ehjbk60sTzhe7n9MVsODLDQuf9v2DGtSikSlN5YhN/l075T6dGt69KnPT0CpVQi2Ck4ZeiiW4ZT9APO1bv8iuWCX67n73Rm+k6C7a3usiFXxzmpRCFlyz9PWZVewC/Kk9RTWgbqVGjM6jnRE5Z0lDFu7jmLE/1o1OeRFdP0xE9Ae3fqH6oevz++ejjv98jMi2p18K+Zofib1u76ejzq99PKSfiNwbzrOy2SWVtao0MLU8evJsM3ECSfE2ltDlcyhfmIqO58eRlMP1u7zCbqYg9dFGfev1lTqaI4pHTyUkcYVoKilp5eJAWz7xoGDTEDdksiY/VMhIjeCdlCR3L6qX7KPnWwyvipRd1pjxi3+pseTTygJn79DSnFOuId9AJSeXMmd5gNWZewz3sov/z/z7bHZ4eWIyX7SM0jlfjNrMIXnRVi6pv7rgWetadE2l1LvTIDVeUOmGnPLR8TujSC86xFg= #DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::7}
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export CONFIG=autoparkstudentproject/cloud-auto-park-configuration-service
  - docker build -t $CONFIG:$COMMIT ./configuration-service
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG
  - export REGISTRY=autoparkstudentproject/cloud-auto-park-authentication-service
  - docker build -t $REGISTRY:$COMMIT ./authentication-service
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY
  - export GATEWAY=autoparkstudentproject/cloud-auto-park-gatewat-service
  - docker build -t $GATEWAY:$COMMIT ./gateway-service
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY
  - export AUTO_PARK_SERVICE=autoparkstudentproject/cloud-auto-park-service
  - docker build -t $AUTO_PARK_SERVICE:$COMMIT ./cloud-auto-park-service
  - docker tag $AUTO_PARK_SERVICE:$COMMIT $AUTO_PARK_SERVICE:$TAG
  - docker push $AUTO_PARK_SERVICE
  - export EUREKA=autoparkstudentproject/cloud-auto-park-eureka-service
  - docker build -t $EUREKA:$COMMIT ./eureka-service
  - docker tag $EUREKA:$COMMIT $EUREKA:$TAG
  - docker push $EUREKA
