logging:
  level:
    org:
      springframework: info
server:
  servlet:
    context-path: /auth-service
  port: 5000
spring:
  datasource:
    driver-class-name=org:
      postgresql: Driver:org.postgresql.Driver
    url: jdbc:postgresql://${POSTRGRES_SERVICE_URL}:${POSTRGRES_SERVICE_PORT}/${POSTRGRES_SERVICE_DB_NAME}
    username: ${POSTRGRES_SERVICE_USERNAME}
    password: ${POSTRGRES_SERVICE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration




