spring:
  datasource:
    driver-class-name=org:
      postgresql: Driver:org.postgresql.Driver
    url: jdbc:postgresql://${POSTRGRES_SERVICE_URL}:${POSTRGRES_SERVICE_PORT}/${POSTRGRES_SERVICE_DB_NAME}
    username: ${POSTRGRES_SERVICE_USERNAME}
    password: ${POSTRGRES_SERVICE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org:
      springframework: info
server:
  servlet:
    context-path: /auto-park-service
  port: 5050

feign:
  hystrix:
    enabled: true
security:
    oauth2:
      client:
        client-id: cloud-auto-park-service
        client-secret: cloud-auto-park-service
        access-token-uri: ${AUTH_SERVICE_URL}/auth-service/oauth/token
        user-authorization-uri: ${AUTH_SERVICE_URL}/auth-service/oauth/authorize
      resource:
        token-info-uri: ${AUTH_SERVICE_URL}/auth-service/oauth/check_token

